#!/usr/bin/env bash
# this script for Install nginx on web server; Nginx should be listening on port 80
# And redirects to another page
# And Have a custom 404 page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://github.com/SHmohamed229 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx start
