#!/usr/bin/env bash
# This for Manages the script manage_my_process.
#   This When passed the argument `start`:
#     1. For Start manage_my_process
#     2. For Create a file PID in /var/run/my_process.pid
#     3. For Display "manage_my_process started"
#   When passed the argument `stop`:
#     1. For Stops manage_my_process
#     2. For Delete the file /var/run/my_process.pid
#     3. For Display "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. For Stops manage_my_process
#     2. For Deletes the file /var/run/my_process.pid
#     3. For Starts manage_my_process
#     4. For Creates a file containing its PID in /var/run/my_process.pid
#     5. For Displays "manage_my_process restarted"
#   If any , displays
#+  "Usage: manage_my_process {start|stop|restart}"

if [ "${1}" == "start" ]

then

    ./manage_my_process &

    touch /var/run/my_process.pid

    echo "$!" > /var/run/my_process.pid

    echo "manage_my_process started"

elif [ "${1}" == "stop" ]

then

    echo "manage_my_process stopped"

    kill "$(cat /var/run/my_process.pid)"

    rm /var/run/my_process.pid

elif [ "${1}" == "restart" ]

then

    kill "$(cat /var/run/my_process.pid)"

    rm /var/run/my_process.pid

    ./manage_my_process &

    touch /var/run/my_process.pid

    echo "$!" > /var/run/my_process.pid

    echo "manage_my_process restarted"

else

    echo "Usage: manage_my_process {start|stop|restart}"

fi
