#!/usr/bin/env bash
# This command for configure Ubuntu Server:
#   for - localhost Resolve to 127.0.0.2
#   for - Facebook.com Resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8__________facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
